### ISSUE TITLE
json.decoder.JSONDecodeError exception

### ISSUE THREAD

**Issue by mattheusv** [devanshuDesai/vim2vsc#1]
I install vim2vsc using pip

`$ pip install vim2vsc`

When I run a simple `vim2vsc` I get this traceback
```
Traceback (most recent call last):
  File "/tmp/bla/venv/bin/vim2vsc", line 11, in <module>
    load_entry_point('vim2vsc==0.1.0', 'console_scripts', 'vim2vsc')()
  File "/tmp/bla/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/bla/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/tmp/bla/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/tmp/bla/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/bla/venv/lib/python3.7/site-packages/vim2vsc/convert.py", line 69, in <module>
    vscode = json.load(file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 36 column 1 (char 961)
```
And, When I try to specify the vimrc file `vim2vsc --vimrc ~/.vimrc `I get same exception

**Comment by devanshuDesai** [comment]
Sorry, this reply is extremely late, but in case you never figured it out. Can I see your `settings.json`? It seems like your `settings.json` isn't formatted properly which is weird. 

Another possible reason could be that your real `settings.json` is located in a different directory than the default location in the tool. I would try explicitly specifying the path of your `settings.json`
